### ISSUE TITLE
How to paste from register in insert mode

### ISSUE THREAD

**Issue by weilbith** [zsh-vi-more/evil-registers#10]
Hey 👋🏾 
I would love to be able to use for example `<Ctrl-w>+` in insert mode to copy from the system clipboard. Is that possible?

**Comment by xPMo** [comment]
Yes, here:

```zsh
vi-set-buffer-and-put-after(){
    zle vi-set-buffer -w
    zle vi-put-after -w
}
zle -N vi-set-buffer-and-put-after
bindkey -M viins '^w' vi-set-buffer-and-put-after
```

This uses the base zle widget names (the plugin overrides them to wrap them), so it will work for the standard vi-buffers even if this plugin isn't loaded.

Depending on the behavior you want when cancelling vi-set-buffer, you may want to use `zle vi-set-buffer -w && zle vi-put-after -w` to prevent putting text. EDIT: Just realized this didn't work, [fixed in `e04f5f0`](https://github.com/zsh-vi-more/evil-registers/commit/e04f5f0b60744107a310b6842aee171f1b4d870a)

**Comment by weilbith** [comment]
Cool! Thanks for your help. I will give this a try very soon.
Do you think you could add this to your plugin? So it just works out of the box?

**Comment by xPMo** [comment]
It's fairly common for users to bind insert-mode `^w` to `backward-kill-word`. In fact, this is the default in Vim (and in the standard emacs ZLE bindings). I won't add it as a default for these reasons, although I would be happy to add it to the README.

The fact that this binding is independent of the use of this plugin also a good reason to not add this.  If you ever want to stop using this plugin, you can keep that custom binding in your Zsh config and it will still work! (ofc without clipboard integrations)

**Comment by weilbith** [comment]
Yes, sorry I was stupid. l was referring to `<Ctrl-r>+` ofc. Sorry for the confusion. Is your answer still the same?

**Comment by xPMo** [comment]
A lot of users (myself included) heavily use history-incremental-search (either the default widget or the fzf-based one) bound to `^R`.  However, since this is a Vim default, I will find a way to opt into it.  Since this functionality is independent to this plugin,  I kind of want to put it in its own plugin.

But I have already set a precedent in [vi-motions](https://github.com/zsh-vi-more/vi-motions) of including similar-but-independent functionality, so I'll do it.

**Comment by xPMo** [comment]
Let me know if [the README additions](https://github.com/zsh-vi-more/evil-registers/compare/dev) are clear.

**Comment by weilbith** [comment]
Perfect! Works like charm! 👌🏾 
I checked out your referenced commit directly. It is not in `master` yet, isn't it?

**Comment by xPMo** [comment]
It is now, and I tagged v3.1 if you prefer releases. Have a good day!

**Comment by weilbith** [comment]
Thank you very much! :hugs:
